version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://server:5001
      # - REACT_APP_API_URL=http://localhost:5001
    depends_on:
      - server
    volumes:
      - ./client:/app/
      # - /app/node_modules
  server:
    build:
      context: ./server
    ports:
      - "5001:5001"
    environment:
      - API_PORT=5001
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    command: npm run start
    depends_on:
      - db
    volumes:
      - ./server:/app/
      # - /app/node_modules
  db:
    build:
      context: ./db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./db:/sql
