version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app/
      - /app/node_modules
  server:
    build:
      context: ./server
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    depends_on:
      - db
    volumes:
      - ./server:/app/
      - /app/node_modules
  db:
    build:
      context: ./db
    image: postgres:13.8-alpine3.16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./db:/sql
