services:
  - type: web
    name: server
    plan: free
    env: docker
    rootDir: server
    envVars:
      - key: API_PORT
        value: 5001
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString      