services:
  - type: web
    name: server
    plan: free
    env: node
    rootDir: server
    envVars:
      - key: API_PORT
        value: 80
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString 
  - type: web
    name: client
    env: static
    buildCommand: npm run build
    staticPublishPath: build
    rootDir: client
    pullRequestPreviewsEnabled: true
    envVars:
      - key: API_URL
        fromService:  
          type: web
          name: server
          envVarKey: RENDER_EXTERNAL_URL
databases:
  - name: db
    plan: free
